const fs = require('fs');
const path = require('path');

function compile(source) {
  const lines = source.split(/\r?\n/);
  const output = [];
  let inJs = false;
  let inHtml = false;
  let block = [];

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;

    if (line === 'js {') {
      inJs = true;
      block = [];
      continue;
    }
    if (line === 'html {') {
      inHtml = true;
      block = [];
      continue;
    }
    if ((inJs || inHtml) && line === '}') {
      if (inJs) output.push(block.join('\n'));
      if (inHtml) output.push(`document.body.insertAdjacentHTML('beforeend', ${JSON.stringify(block.join('\n'))});`);
      inJs = false;
      inHtml = false;
      block = [];
      continue;
    }
    if (inJs || inHtml) {
      block.push(raw);
      continue;
    }

    const openWindow = line.match(/^Openwindow\(js\s+code\((.*)\)\)$/s);
    if (openWindow) {
      output.push(`JVE.openWindow(${JSON.stringify(openWindow[1])});`);
      continue;
    }

    if (/^Openwindow\(/.test(line) && !openWindow) {
      throw new Error(`JVE error on line ${i + 1}: Openwindow requires the exact form Openwindow(js code(HTML))`);
    }

    const echo = line.match(/^echo\s+["'](.*)["']$/);
    if (echo) {
      output.push(`console.log(${JSON.stringify(echo[1])});`);
      continue;
    }

    const alert = line.match(/^alert\s+["'](.*)["']$/);
    if (alert) {
      output.push(`window.alert(${JSON.stringify(alert[1])});`);
      continue;
    }

    const set = line.match(/^set\s+(\w+)\s+(.+)$/);
    if (set) {
      output.push(`let ${set[1]} = ${parseValue(set[2])};`);
      continue;
    }

    const get = line.match(/^get\s+["'](.+?)["']\s+as\s+(\w+)$/);
    if (get) {
      output.push(`fetch(${JSON.stringify(get[1])}).then(r => r.json()).then(${get[2]} => window.${get[2]} = ${get[2]});`);
      continue;
    }

    const inject = line.match(/^inject\s+js\s+["'](.+)["']$/);
    if (inject) {
      output.push(`const s=document.createElement('script');s.src=${JSON.stringify(inject[1])};document.head.appendChild(s);`);
      continue;
    }

    throw new Error(`JVE error on line ${i + 1}: ${raw}`);
  }

  return `// Generated by JVE\n(function(){\n${output.join('\n')}\n})();\n`;
}

function parseValue(value) {
  if (/^["'].*["']$/.test(value)) return JSON.stringify(value.slice(1, -1));
  if (/^(true|false|null)$/.test(value)) return value;
  if (/^-?\d+(\.\d+)?$/.test(value)) return value;
  return value;
}

if (require.main === module) {
  const file = process.argv[2];
  if (!file) {
    console.error('Usage: node compiler/compiler.js <file.jve>');
    process.exit(1);
  }
  const source = fs.readFileSync(path.resolve(file), 'utf8');
  process.stdout.write(compile(source));
}

module.exports = { compile };
